# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20160512_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Normal'), (3, 'Urgent')]),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Finished')]),
        ),
    ]
